on:
   push:
     branches:
           - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
           - uses: actions/checkout@v3
           - name: "login"
             run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password   ${{ secrets.DOCKER_PASSWORD }}
           - name: "building docker image"
             run: docker build -t ${{ secrets.DOCKER_USERNAME }}/project .
           - name: "building docker hub"
             run: docker push  ${{ secrets.DOCKER_USERNAME }}/project 

 