on:
   push:
     branches:
           - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
           - uses: actions/checkout@v3
           - name: "login"
             run: docker login --username ${{ secrets.docker-username }} --password   ${{ secrets.docker-password }}
           - name: "building docker image"
             run: docker build -t  ${{ secrets.docker-username }}/project
           - name: "building docker hub"
             run: docker push  ${{ secrets.docker-username }}/project 

 